# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 00:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosario_construction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_info',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
    ]
